# Mount code for hot reloading and cache for faster compile in dev mode.
version: '3.1'

services:

  civiform:
    build: ..
    volumes:
      - ../universal-application-tool:/usr/src/universal-application-tool
      - ~/.coursier:/root/.coursier
      - ~/.sbt:/root/.sbt
      - ~/.ivy:/root/.ivy2
